### ISSUE TITLE
Worker is not define

### ISSUE THREAD

**Issue by pimpannt** [nimiq/qr-scanner#110]
Here is my code to read image from file. I got Worker is not define, what I need to do to solve it please...

```
const QrScanner = require('qr-scanner');
QrScanner.WORKER_PATH = '/Users/xxx/Documents/node-qr-scan/node_modules/qr-scanner/qr-scanner-worker.min.js';

const file = '/Users/xxx/Documents/node-qr-scan/gettyimages-1066110176.jpg';
if (!file) {
    return;
}
QrScanner.scanImage(file)
    .then(result => setResult(fileQrResult, result))
    .catch(e => setResult(fileQrResult, e || 'No QR code found.'));
```

**Comment by sisou** [comment]
Hi! How are you serving the HTML and Javascript file in question? Do you use a `localhost` server?  In that case you would need to specify the path to the worker relative to the HTML file that you are loading.

Or are you using it in NodeJS?

**Comment by mrWiga** [comment]
Did you work it out?

**Comment by danimoh** [comment]
Likely an issue of how the files are being served or a wrong WORKER_PATH, see https://github.com/nimiq/qr-scanner#setting-up-the-worker.
Also see https://github.com/nimiq/qr-scanner/issues/11 and https://github.com/nimiq/qr-scanner/issues/13.

Please reopen, if you continue to encounter issues.

**Comment by danimoh** [comment]
For anyone struggling with this:
The api has been simplified now.
Specifying the WORKER_PATH is not required anymore in the newest release, have a look at the readme :)

**Comment by natsu90** [comment]
I have similar issue running this in NodeJS, below is the error message;

```
Note that the return type of scanImage will change in the future. To already switch to the new api today, you can pass returnDetailedScanResult: true.

ReferenceError: window is not defined
    at e.createQrEngine (/Users/sulaiman/Workspace/chipin/examples/node_modules/qr-scanner/qr-scanner.umd.min.js:18:358)
    at e.scanImage (/Users/sulaiman/Workspace/chipin/examples/node_modules/qr-scanner/qr-scanner.umd.min.js:14:472)
    at /Users/sulaiman/Workspace/chipin/examples/app.js:90:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/Users/sulaiman/Workspace/chipin/examples/node_modules/qr-scanner/qr-scanner.umd.min.js:30
c("Image load error"):b()};a.addEventListener("load",d);a.addEventListener("error",d)})}static async _postWorkerMessage(a,b,c,d){return e._postWorkerMessageSync(await a,b,c,d)}static _postWorkerMessageSync(a,b,c,d){if(!(a instanceof Worker))return-1;let f=e._workerMessageId++;a.postMessage({id:f,type:b,data:c},d);return f}}e.DEFAULT_CANVAS_SIZE=400;e.NO_QR_CODE_FOUND="No QR code found";e._disableBarcodeDetector=!1;e._workerMessageId=0;return e})
                                                                                                                                                                                                                                         ^

ReferenceError: Worker is not defined
    at e._postWorkerMessageSync (/Users/sulaiman/Workspace/chipin/examples/node_modules/qr-scanner/qr-scanner.umd.min.js:30:234)
    at e._postWorkerMessage (/Users/sulaiman/Workspace/chipin/examples/node_modules/qr-scanner/qr-scanner.umd.min.js:30:139)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by natsu90** [comment]
for those looking to decode QR using NodeJS, can use `jsqr` library instead, https://dev.to/kshyun28/how-to-reliably-read-qr-codes-in-nodejs-502i
