### ISSUE TITLE
Can't scan image element on page

### ISSUE THREAD

**Issue by snowman** [nimiq/qr-scanner#252]
```html
<script src="https://cdn.jsdelivr.net/npm/qr-scanner@1.4.2/qr-scanner.umd.min.js"></script>
```

```javascript
const imgElement = document.querySelector("img")

if (!imgElement) {
  throw "imgElement not found"
}

QrScanner.scanImage(imgElement)
  .then(result => {
    if (result) {
      alert("QR Code content: " + result)
    } else {
      alert("No QR Code found in the image.")
    }
  })
  .catch(error => {
    console.error(error)
  })
```

shows error
```error
TypeError: Failed to resolve module specifier './qr-scanner-worker.min.js'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
    at a (qr-scanner.umd.min.js:18:279)
    at e.createQrEngine (qr-scanner.umd.min.js:18:477)
    at e.scanImage (qr-scanner.umd.min.js:14:472)
    at <anonymous>:7:11
```

Jump to the error line:
```error
            a = ()=>import("./qr-scanner-worker.min.js").then(c=>c.createWorker());
```

**Comment by snowman** [comment]
<del>don't forget to add `qr-scanner-worker.min.js` dependency! document does not talk that?</del>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- <script src="qr-scanner-worker.min.js"></script> -->
    <script src="qr-scanner.umd.min.js"></script>
  </head>
  <body>
    <img src="f9907bc5c6506f31d3980a0669f63c42.jpg" />
    <script>
      const imgElement = document.querySelector("img")

      if (!imgElement) {
        throw "imgElement not found"
      }

      QrScanner.scanImage(imgElement)
        .then(result => {
          if (result) {
            alert("QR Code content: " + result)
          } else {
            alert("No QR Code found in the image.")
          }
        })
        .catch(error => {
          console.error(error)
        })
    </script>
  </body>
</html>
```

Okay, I don't know why, but it works on Firefox, maybe extension block usage on Vivaldi
